name: "Build & run"
cmd: cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr && make && ./src/konv
sh: true
errorMatch: (?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+)\.(?<col>\\d+)\-(?<line_end>\\d+)\.(?<col_end>\\d+):\\s+(?<message>.+)

# MainWindow.vala:127.33-127.33: error: syntax error, expected identifier
