# First we define the valac version(s) targeted
vala-version = ">=0.30.0"

# Basic informations about our app
name = "konv"
description = "Secure P2P instant messenger"

# Use semantic versionning
version = "0.1.0"

# To help find your project
keywords = [
  "konv", "instant messaging", "messenger", "chat", "p2p", "encrypted",
  "encryption", "secure", "user-friendly", "skype-like", "tox", "toxcore"
]
license = "MIT"

homepage = "https://konv.im"
repository = "https://github.com/SkyzohKey/Konv.git"

# Where to report bugs
bugs = {
  email = "contact@konv.im",
  url = "https://github.com/SkyzohKey/Konv/issues"
}

# Dev team members informations.
author = "SkyzohKey <skyzohkey@konv.im>"
contributors = []
maintainers = [
  "SkyzohKey <skyzohkey@konv.im>"
]

# The files to compile, supports wildcard (*).
files = [
  "src/core/*.vala",
  "src/gui/components/*.vala",
  "src/gui/widgets/*.vala",
  "src/gui/windows/*.vala",
  "src/*.vala",
]

# VAPIs directory.
vapi-dir = "src/vapis/"

# Custom output path, if not specified defaults to `build/$(app-name)`.
output = "build/konv"

# Other arguments to give to valac.
compilerParams = [
  "-DGETTEXT_PACKAGE", "konv"
]

# If true, we add flags to compile as a library
library = false

# Poulp has support for npm-like scripts.
[scripts]
run = [ "poulp build", "./$(POULP_BUILD_OUPUT)" ]

[dependencies]
"gio-2.0" = "*"
"gtk+-3.0" = "*"
"json-glib-1.0" = "*"
"libtoxcore" = ">=0.1.0"
"libtoxav" = ">=0.1.0"

[dev-dependencies]
valadate = "^0.1.0"
